export const accounts = [
  {
    accountId: "1234-4567-3456-3456",
    balance: {
      usd: "25.620,00",
      euro: "76.451,00",
      gbp: "30.100,00",
    },
    transactions: [
      {
        name: '"Golub" Taxi Transportation',
        date: "20th May, 18:39",
        amount: "-345,00",
        paymentType: "EUR",
        isPositive: false,
        purpose: "taxi",
      },
      {
        name: '"Francois" Restaurant Dinner',
        date: "15th May, 20:56",
        amount: "-1.158,00",
        paymentType: "EUR",
        isPositive: false,
        purpose: "restaurant",
      },
      {
        name: '"AirMax" Travel to Paris',
        date: "14th May, 16:00",
        amount: "-813,00",
        paymentType: "EUR",
        isPositive: false,
        purpose: "travel",
      },
      {
        name: "Construction ltd.",
        date: "11th May, 09:26",
        amount: "+24.500,00",
        paymentType: "USD",
        isPositive: true,
        purpose: "business",
      },
      {
        name: "Robert Smith",
        date: "03rd  May, 12:06",
        amount: "+11.215,00",
        paymentType: "USD",
        isPositive: true,
        purpose: "personal",
      },
    ],
  },
  {
    accountId: "4321-5678-1234-5678",
    balance: {
      usd: "10.000,00",
      euro: "0",
      gbp: "0",
    },
    transactions: [
      {
        name: "Airbnb",
        date: "1st Jan, 14:30",
        amount: "-500.00",
        paymentType: "USD",
        isPositive: false,
        purpose: "travel",
      },
      {
        name: "Uber",
        date: "1st Jan, 15:30",
        amount: "-50.00",
        paymentType: "USD",
        isPositive: false,
        purpose: "taxi",
      },
      {
        name: "John Doe",
        date: "1st Jan, 16:30",
        amount: "+200.00",
        paymentType: "USD",
        isPositive: true,
        purpose: "personal",
      },
      {
        name: "Acme Corp",
        date: "1st Jan, 17:30",
        amount: "+1000.00",
        paymentType: "USD",
        isPositive: true,
        purpose: "business",
      },
      {
        name: "Joe's Diner",
        date: "1st Jan, 18:30",
        amount: "-100.00",
        paymentType: "USD",
        isPositive: false,
        purpose: "restaurant",
      },
    ],
  },
  {
    accountId: "5689-5678-1234-5678",
    balance: {
      usd: "10.000,00",
      euro: "0",
      gbp: "0",
    },
    transactions: [
      {
        name: "Expedia",
        date: "1st Jan, 14:30",
        amount: "-1000.00",
        paymentType: "USD",
        isPositive: false,
        purpose: "travel",
      },
      {
        name: "Lyft",
        date: "1st Jan, 15:30",
        amount: "-20.00",
        paymentType: "USD",
        isPositive: false,
        purpose: "taxi",
      },
      {
        name: "John Doe",
        date: "1st Jan, 16:30",
        amount: "+500.00",
        paymentType: "USD",
        isPositive: true,
        purpose: "personal",
      },
      {
        name: "Acme Inc",
        date: "1st Jan, 17:30",
        amount: "+5000.00",
        paymentType: "USD",
        isPositive: true,
        purpose: "business",
      },
      {
        name: "Tesco",
        date: "20th Mar, 12:00",
        amount: "-50.00",
        paymentType: "USD",
        isPositive: false,
        purpose: "restaurant",
      },
    ],
  },
  {
    accountId: "2345-6789-2345-6789",
    balance: {
      usd: "0",
      euro: "10.000,00",
      gbp: "0",
    },
    transactions: [
      {
        name: "Ryanair",
        date: "5th Feb, 10:15",
        amount: "-500.00",
        paymentType: "EUR",
        isPositive: false,
        purpose: "travel",
      },
      {
        name: "Taxi Berlin",
        date: "5th Feb, 11:15",
        amount: "-50.00",
        paymentType: "EUR",
        isPositive: false,
        purpose: "taxi",
      },
      {
        name: "Jane Smith",
        date: "5th Feb, 12:15",
        amount: "+200.00",
        paymentType: "EUR",
        isPositive: true,
        purpose: "personal",
      },
      {
        name: "Boeing Corp",
        date: "5th Feb, 13:15",
        amount: "+1000.00",
        paymentType: "EUR",
        isPositive: true,
        purpose: "business",
      },
      {
        name: "Salt Bae",
        date: "9th Feb, 14:00",
        amount: "-1000.00",
        paymentType: "EUR",
        isPositive: false,
        purpose: "restaurant",
      },
    ],
  },
]
